// Code generated by "stringer -type MsgType,SCMGType -linecomment -output constant_string.go"; DO NOT EDIT.

package sccp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgTypeCR-1]
	_ = x[MsgTypeCC-2]
	_ = x[MsgTypeCREF-3]
	_ = x[MsgTypeRLSD-4]
	_ = x[MsgTypeRLC-5]
	_ = x[MsgTypeDT1-6]
	_ = x[MsgTypeDT2-7]
	_ = x[MsgTypeAK-8]
	_ = x[MsgTypeUDT-9]
	_ = x[MsgTypeUDTS-10]
	_ = x[MsgTypeED-11]
	_ = x[MsgTypeEA-12]
	_ = x[MsgTypeRSR-13]
	_ = x[MsgTypeRSC-14]
	_ = x[MsgTypeERR-15]
	_ = x[MsgTypeIT-16]
	_ = x[MsgTypeXUDT-17]
	_ = x[MsgTypeXUDTS-18]
	_ = x[MsgTypeLUDT-19]
	_ = x[MsgTypeLUDTS-20]
}

const _MsgType_name = "CRCCCREFRLSDRLCDT1DT2AKUDTUDTSEDEARSRRSCERRITXUDTXUDTSLUDTLUDTS"

var _MsgType_index = [...]uint8{0, 2, 4, 8, 12, 15, 18, 21, 23, 26, 30, 32, 34, 37, 40, 43, 45, 49, 54, 58, 63}

func (i MsgType) String() string {
	i -= 1
	if i >= MsgType(len(_MsgType_index)-1) {
		return "MsgType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SCMGTypeSSA-1]
	_ = x[SCMGTypeSSP-2]
	_ = x[SCMGTypeSST-3]
	_ = x[SCMGTypeSOR-4]
	_ = x[SCMGTypeSOG-5]
	_ = x[SCMGTypeSSC-6]
}

const _SCMGType_name = "SSASSPSSTSORSOGSSC"

var _SCMGType_index = [...]uint8{0, 3, 6, 9, 12, 15, 18}

func (i SCMGType) String() string {
	i -= 1
	if i >= SCMGType(len(_SCMGType_index)-1) {
		return "SCMGType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SCMGType_name[_SCMGType_index[i]:_SCMGType_index[i+1]]
}
